### ISSUE TITLE
Documentation link broken - working link included

### ISSUE THREAD

**Issue by guhan-lily** [resample-project/resample#101]
Documentation that is linking to at `https://resample.readthedocs.io/en/latest/` is broken.

This works though `https://resample.readthedocs.io/en/master/index.html`

**Comment by dsaxton** [comment]
Thanks @guhan-lily for the issue. `https://resample.readthedocs.io/en/latest/` is working for me, do you mean linking between that page and the actual API docs is what's broken?

cc @HDembinski

**Comment by HDembinski** [comment]
Thanks for reporting, I will investigate, too.

**Comment by guhan-lily** [comment]
Sorry, I was dozing at the keyboard when I entered tat issue. The link itself is not broken but there are no further navigational links there.

**Comment by HDembinski** [comment]
Yes, I noticed when I had a look, thank you for reporting this. This broke when I tried to update the docs recently. I will fix this. It is good that RTD points to master by default. Latest shows the state of the development branch.

**Comment by HDembinski** [comment]
Hm, when I compile the docs locally, it works.

**Comment by HDembinski** [comment]
https://readthedocs.org/projects/resample/builds/14116549

```
WARNING: autodoc: failed to import module 'bootstrap' from module 'resample'; the following exception was raised:
No module named 'numpy'
WARNING: autodoc: failed to import module 'empirical' from module 'resample'; the following exception was raised:
No module named 'numpy'
looking for now-outdated files... WARNING: autodoc: failed to import module 'jackknife' from module 'resample'; the following exception was raised:
No module named 'numpy'
WARNING: autodoc: failed to import module 'permutation' from module 'resample'; the following exception was raised:
No module named 'numpy'
none found
```

Seems we are missing numpy as a dependency for the docs build.
