### ISSUE TITLE
Feature request: Allow passing several arrays to `resample.bootstrap.resample` and similar functions

### ISSUE THREAD

**Issue by JohannesWiesner** [resample-project/resample#112]
First of all, thank you for implementing this package! I [came across this thread on StackOverflow](https://stackoverflow.com/questions/43151401/bootstrapping-multiple-regression-parameters-in-python), this is how I found the resample package. I have some suggestions for further improving the user experience when using `resample` package. 

1. ) It would be nice, if the user could pass `X` and `y` separately instead of passing one array to the `bootstrapping` function and then splitting it again into `X` and `y` within the function that is passed to `bootstrapping`. For instance, for my current project, I had already started off with `X` and `y` separately from the beginning. But in order to use `bootstrap` I had to concatenate them first only to separate them again a few steps later within the function. 

2.) It would maybe make sense if the function could also accept further `**args` and not only a `np.array`? This would for instance allow to safely pass a `Pipeline`  or `Estimator` object to `bootstrap`?

**Comment by dsaxton** [comment]
Hi @JohannesWiesner, thanks for your interest. I think that's a reasonable idea, but arguments could be made either way in my opinion. It would be convenient in some cases to pass two arguments, but on the other hand when we sample we're really only ever drawing from a single (possibly multivariate, including both X and y) distribution and I think making this explicit could be seen as a good thing. If the two were separate the first thing we'd have to do would be to concatenate to keep everything aligned anyways, so this would really just be hiding that fact as well as complicating the function signature.

To your second point, I think any iterable can be resampled, but I'm not sure if it would be possible to sample custom sklearn objects like `Pipeline` and `Estimator`.

Any thoughts @HDembinski?

**Comment by HDembinski** [comment]
At first glance, I agree with @dsaxton but let me think about it. The main problem with adding "convenience" like this is that this often introduces unintended side effects and we have to make sure that it does not introduce ambiguities. Maybe it is harmless here to follow your suggestion, but it needs some thought. The goal is to make bootstrapping work with any function-like object that acts like a pure function (does not have visible side effects). If it does not work with a sklearn Pipeline, let us know.

**Comment by HDembinski** [comment]
@JohannesWiesner A few requests for you if you want us to react property:
- I know what `Pipeline` is by chance, but not `Estimator`. If you refer to classes of other libraries, add a link to the library , and ideally directly to the documentation page of that class.
- There is no `bootstrapping` function in `resample`. I assume you mean `resample.bootstrap.bootstrap`, but you need to be specific what you are talking about. We cannot guess what you mean.

**Comment by JohannesWiesner** [comment]
@HDembinski, [here's the documentation to the BaseEstimator class ](https://scikit-learn.org/stable/developers/develop.html#estimators)from scikit-learn. Basically, this is the class that all classifier and regressor classes in scikit-learn inherit from. Thus, they all have the same set of methods such as `.fit()`, `.fit_transform()` or `.predict()`. A `Pipeline` object is basically a chain of `BaseEstimators`. 

Sorry, for the typo! Of course, I meant `resample.bootstrap.bootstrap`.

**Comment by HDembinski** [comment]
Thanks! That's helpful.

**Comment by HDembinski** [comment]
@dsaxton 

Currently, our functions look like this:

`func(Iterable, *options)`

or like this

`func(Callable, Iterable, *options)`

I think it would be good style to make all options keyword-only parameters. This is another breaking change, however. This would allow us to change the signatures to

`func(*Iterables, **options)`

`func(Callable, *Iterables, **options)`

Which would allow Johannes to write

```
for Xb, yb in resample.bootstrap.resample(X, y):
    # do stuff with Xb, yb
```

**Comment by dsaxton** [comment]
> which would be pretty neat. What do you think?

Seems pretty reasonable to me provided you don't think it's too difficult a change to make. I like the idea of making options keyword only since it also forces more explicit code and helps avoid certain mistakes.
