### ISSUE TITLE
Consistent permutation test results in existing release (1.0.1) vs project head (1.1.0)

### ISSUE THREAD

**Issue by asalcedo29** [resample-project/resample#114]
Hi - Wanted to know if the results of a ttest permutation test pvalues are consistent between both versions (conda installer gives me version 1.0.1) which is different from code in project head (which is 1.1.0). My question relates the output of the test; in the 1.0.1 version the calculation is made using `np.mean(permute_t <= t)` while in the head version the pvalue is obtained by `np.mean(np.abs(ts) > np.abs(t))`. It seems that the comparisson logic is flipped between both (so not sure if pvalue in 1.0.1 version would be obtained by `1-np.mean(permute_t <= t)`. 

Thanks for clarifying!

**Comment by HDembinski** [comment]
@asalcedo29 Thank you very much for the comment, I will check this. I recently did a rewrite of the tests and I noticed some discrepancies between the implementation and what I found in references. So it may be that, but I will check again. Perhaps I just introduced a mistake.

**Comment by asalcedo29** [comment]
Thanks for the response @HDembinski . Wondering if when you tested this the results you got were consistent between the new version and the existing release. Also, is there a plan to update the version to 1.1.0?

**Comment by HDembinski** [comment]
Yes, once the work on the permutation tests is finished.

**Comment by HDembinski** [comment]
Ok, I finally checked this. The new implementation is consistent with scipy.stats.ttest_ind, so the change was intended. Either way, I hope there was no change in the p-value even if the definition of the test statistic is now different.

```py
>>> from resample.permutation import ttest
>>> from scipy.stats import ttest_ind
>>> rng = np.random.default_rng(1)
>>> x = rng.normal(5, 2, size=100)
>>> y = rng.normal(3, 2, size=100)
>>> z = rng.normal(5, 2, size=100)
>>> ttest(x, x)
<PermutationResult statistic=0.0 pvalue=1.0 samples=[-1.0777184701737819 -0.5745783892613265 0.5535158154032149 ... 0.363142920966484 0.07527169151096517 0.5200998397771814]>>>> ttest(x, y)
>>> ttest(x, y)
<PermutationResult statistic=8.023556336493108 pvalue=0.0 samples=[-1.003702204153944 -2.235627507559989 -1.2326224127000487 ... 1.901142803116256 0.2923358962730485 0.26104067024073224]>
>>> ttest(x, z)
<PermutationResult statistic=-0.4048640806245116 pvalue=0.702 samples=[0.7605887004737174 1.1012141703433986 2.0505963468370663 ... -0.087491970163202 0.3842311706617004 -0.5125530333345881]>
>>> ttest_ind(x, x)
Ttest_indResult(statistic=0.0, pvalue=1.0)
>>> ttest_ind(x, y)
Ttest_indResult(statistic=8.023556336493108, pvalue=8.868335948218041e-14)
>>> ttest_ind(x, z)
Ttest_indResult(statistic=-0.4048640806245117, pvalue=0.6860144778466251)
```
