### ISSUE TITLE
Move resample to an organisation on github?

### ISSUE THREAD

**Issue by HDembinski** [resample-project/resample#57]
Since we are both actively working on the project, it would be nice to move the repository to an organization.

I reserved https://github.com/resample-project in case you agree? We would both be owners.

**Comment by dsaxton** [comment]
> Since we are both actively working on the project, it would be nice to move the repository to an organization.
> 
> I reserved https://github.com/resample-project in case you agree? We would both be owners.

Yes, I agree with moving it off my personal GitHub, and resample-project sounds like a good name

**Comment by dsaxton** [comment]
@HDembinski Is there a way to migrate everything over to resample-project (issues, PRs, etc.)?

**Comment by HDembinski** [comment]
Yes, if you transfer the repo to the org, it retains everything. The old location will even automatically forward to the new location. You need to go to https://github.com/dsaxton/resample/settings and scroll down to "transfer ownership". I did this before for iminuit, it was painless.
