### ISSUE TITLE
Switch to two-branch `master` + `develop` model

### ISSUE THREAD

**Issue by HDembinski** [resample-project/resample#70]
Most professional repos use a two-branch model with `master` and `develop` (Boost, Scikit-HEP...), I think we should switch to that.

develop:
- default branch, commits and PRs go there
- force updates allowed but should be kept to an absolute minimum
- forks/feature branches are based on develop 
- gets rebased to master if master was updated for a release
- RTD "latest" build points to develop

master:
- never force-updated (can and should be turned off in the settings)
- only updated on making a release
- on release, merge develop into master, update version number and changelog, make release
- special CI jobs that check the release are only triggered on updates to master
- RTD "stable" build points to master and is shown by default

The two main advantages of this scheme are that
- one can have special CI jobs that check releases, which are only triggered on updates to master
- one can have RTD point to the latest release automatically (using the "stable" build)

**Comment by dsaxton** [comment]
> Most professional repos use a two-branch model with `master` and `develop` (Boost, Scikit-HEP...)

Are you sure this is the case? None of the major projects I just checked seem to do this (pandas, dask, scikit-learn); it looks like they commit to master and then release from master, unless I'm misreading. I kind of like that approach as well as it keeps a more granular view of history (with random PR noise squashed) on the master branch.

**Comment by HDembinski** [comment]
The commit history remains the same. It is like what we do now, except that we have two branches, with one lagging behind the other (being updated only on releases). The approach has no cons only pros. Aren't boost.org and Scikit-HEP good enough references?

**Comment by HDembinski** [comment]
pybind11 also uses this model, but they call `develop` -> `master` and the release branch `stable`. 
https://github.com/pybind/pybind11/tree/stable

**Comment by HDembinski** [comment]
To prove to you that this is a standard thing, here is the model described:
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by HDembinski** [comment]
We don't need to do it exactly like it is laid out there, the master branch doesn't have to squash all the commits of the develop branch, it can just merge them in.

**Comment by dsaxton** [comment]
Cool, as long as it doesn't lose any granularity in the master git log (i.e., we aren't squash merging from develop to master) I don't have too strong of an opinion. I'd likely want to use a "rebase-only" approach when merging develop into master.

**Comment by HDembinski** [comment]
Ok, agreed!

**Comment by dsaxton** [comment]
@HDembinski FYI I updated the default branch for this repo

**Comment by HDembinski** [comment]
Thanks, I think we can close this then.
