### ISSUE TITLE
Azure pipelines not running

### ISSUE THREAD

**Issue by dsaxton** [resample-project/resample#74]
Noticed that Azure pipelines don't seem to be running for PRs or commits to master so currently no tests are being executed in CI. From what I can tell the last successful run was from https://github.com/resample-project/resample/pull/65.

This may have something to do with transferring the repo to this project (the pipelines were being run in my personal Azure account); is this a good opportunity to switch over to doing everything with GitHub Actions?

cc @HDembinski

**Comment by HDembinski** [comment]
I like GitHub Actions a lot, so I am all for that.
