### ISSUE TITLE
confidence_interval with bca method potentially fails for limited estimators

### ISSUE THREAD

**Issue by HDembinski** [resample-project/resample#84]
The BCa method fails if the estimator is bounded and a lot of samples end up at the bound. Some example to demonstrate this:

```py
from resample.bootstrap import confidence_interval as ci
from scipy.stats import norm
import numpy as np

rng = np.random.default_rng(1)

def estimator(data):
    return max(np.mean(data), 0.0)
    
for ntry in range(10):
    data = rng.normal(size=30)
    x = estimator(data)
    print(ci(estimator, data, random_state=rng))
```
produces
```
(nan, nan)
(nan, nan)
(0.0, 0.3788733184819861)
(0.0, 0.49981428936200234)
(0.0, 0.5315212694331907)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(0.0, 0.7164693404819538)
```
The problem seems to originate from the acceleration, `den` becomes zero and then `acc` is NaN.

I don't think this is an implementation error, it is rather that the original BCa method does not work for this case and needs some modification.

**Comment by dsaxton** [comment]
I think raising a helpful warning explaining why a meaningful result wasn't computed makes sense, whatever we decide the return value should be

**Comment by HDembinski** [comment]
Let's discuss in the PR.
