### ISSUE TITLE
Need cool logo for resample

### ISSUE THREAD

**Issue by HDembinski** [resample-project/resample#88]
Every cool project needs a cool logo. @dsaxton any ideas?

**Comment by HDembinski** [comment]
Some logos I made in the past

![grafik](https://user-images.githubusercontent.com/2631586/98601944-02cdea00-22e0-11eb-9321-bb3d9f56cc50.png)

![grafik](https://user-images.githubusercontent.com/2631586/98601998-1416f680-22e0-11eb-82c9-7e4d43c68370.png)

![grafik](https://user-images.githubusercontent.com/2631586/98602545-f1391200-22e0-11eb-8065-034f676f521e.png)

Wow, putting all those together shows a preference for red, blue, white, black.

**Comment by dsaxton** [comment]
Looks really good, how did you make those? I've had some ideas floating around in my head, just not sure how I'd put them into a graphic. Something resembling repetition could be interesting, like the word "resample" repeated a few times in overlapping text but fading into the background. I'm not a graphic designer, so it's entirely possible this would look terrible :smile:

**Comment by HDembinski** [comment]
I use inkscape since it is FOSS, the raw logos are saved in svg format before eventually rasterizing them as needed.

I like your ideas. Something based on the string "resample" seems like a good idea.
