### ISSUE TITLE
Add USP permutation test from Richard Samworth

### ISSUE THREAD

**Issue by HDembinski** [resample-project/resample#89]
https://indico.cern.ch/event/1036527/attachments/2243646/3804631/RichardSamworth_PHYSTAT.pdf

**Comment by HDembinski** [comment]
@dsaxton Do you know of this test? I just watched the presentation and it looks very good.

**Comment by HDembinski** [comment]
On slide 22 it is shown that the power of the USP test is better than two other popular tests and it also has the property of giving exact type 1 errors.

**Comment by dsaxton** [comment]
@HDembinski I hadn't heard of this but looks really interesting (in my experience testing for independence is very useful even for doing basic data exploration / preprocessing for modeling). I'd need to look at this more carefully (and get rid of some mental cobwebs), but nice to see research still being done on this classic problem.
